///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntity {
/*
{
  "code": "1",
  "title": "Adalet Bakanlığı",
  "link": "http://www.adalet.gov.tr/",
  "tel": "03124177770",
  "email": "info@adalet.gov.tr",
  "adres": "Vekaletler Cad. Kızılay / ANKARA"
} 
*/

  String? code;
  String? title;
  String? link;
  String? tel;
  String? email;
  String? adres;

  SomeRootEntity({
    this.code,
    this.title,
    this.link,
    this.tel,
    this.email,
    this.adres,
  });
  SomeRootEntity.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    title = json['title']?.toString();
    link = json['link']?.toString();
    tel = json['tel']?.toString();
    email = json['email']?.toString();
    adres = json['adres']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['title'] = title;
    data['link'] = link;
    data['tel'] = tel;
    data['email'] = email;
    data['adres'] = adres;
    return data;
  }
}
